# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-10 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=32, verbose_name='密码'),
        ),
    ]
